server:
  port: 8080
spring:
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: true
        web-allow-others: false
  application:
    name: rabbitmq-teste
  datasource:
    url: jdbc:h2:mem:example-app;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password: null
    driverClassName: org.h2.Driver
    generate-unique-name: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        default-requeue-rejected: false
        retry:
          enabled: true
          max-attempts: 1
          multiplier: 1
          initial-interval: 2000
     
              
  
  jackson:
    deserialization:
      fail-on-unknown-properties: false
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false